<a href="https://colab.research.google.com/github/anandvardhan09/PyTorch/blob/main/00_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


# New Section

In [ ]:
torch.arange(1,11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
torch.arange(start=0, end=1000, step =22)


tensor([  0,  22,  44,  66,  88, 110, 132, 154, 176, 198, 220, 242, 264, 286,
        308, 330, 352, 374, 396, 418, 440, 462, 484, 506, 528, 550, 572, 594,
        616, 638, 660, 682, 704, 726, 748, 770, 792, 814, 836, 858, 880, 902,
        924, 946, 968, 990])

In [ ]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,#what datatype is the tensor
                               device=None,#what device is your tensor on
                               requires_grad=False)#whether or not to track gradients
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])